#!/bin/bash
if [ ! -f /etc/udev/rules.d/80-movidius.rules  ]; then
    echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | tee /etc/udev/rules.d/80-movidius.rules
    udevadm control --reload-rules && udevadm trigger
fi
