#!/bin/bash
if [ ! -f /etc/udev/rules.d/80-movidius.rules ]; then
    mkdir -p /etc/udev/rules.d/
    echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | tee /etc/udev/rules.d/80-movidius.rules > /dev/null
    # Determine if it is a Docker environment
    if [ ! -f /.dockerenv ]; then
        udevadm control --reload-rules && udevadm trigger
    fi
fi
