# This is a basic workflow to help you get started with Actions

name: Build Depthai-ros Armv7 Debs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm/v7]
        image:
          - kinetic_depthai_xenial
          - melodic_depthai_bionic
          - noetic_depthai_focal

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build Debs
        uses: addnab/docker-run-action@v3
        with:
          image: richardarducam/ros:${{ matrix.image }}
          shell: bash
          options: -v ${{ github.workspace }}:/workdir --platform ${{ matrix.platform }} -e DEBIAN_FRONTEND=noninteractive
          run: |
            if [ $(lsb_release -c -s) != "buster" ]; then 
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv B43AA98A456BA62E7D0FC2570FFB30A4102243D5 \
            && echo "deb http://ppa.launchpadcontent.net/richard-deng/cmake/ubuntu $(lsb_release -c -s) main" | sudo tee /etc/apt/sources.list.d/richard-deng-ubuntu-cmake.list
            fi
            mkdir -p /home/ubuntu/.hunter
            sudo mkdir -p /usr/local/share/keyrings
            curl -fsSL https://richard-xx.github.io/ros-depthai-repo/PUBLIC.KEY | gpg --dearmor | sudo tee /usr/local/share/keyrings/ros-depthai-repo.gpg > /dev/null
            echo "deb [signed-by=/usr/local/share/keyrings/ros-depthai-repo.gpg] https://richard-xx.github.io/ros-depthai-repo $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros-depthai-repo.list
            sudo apt update
            sudo apt install -y udev 
            sudo apt install -y ros-${ROS_DISTRO}-depthai ros-${ROS_DISTRO}-foxglove-msgs
            sudo apt install -y ros-${ROS_DISTRO}-depthai-ros
            sudo apt upgrade -y
            bash build.sh -r

      - uses: actions/upload-artifact@v3
        with:
          name: depthai-ros
          path: artifacts/*
